parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    # Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'

    App\Service\AuthService:
        arguments:
            $serverUrl: '%env(AUTH_URL)%'
            # $session: '@session'

    App\EventListener\AuthListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    Predis\Client:
        arguments:
            - '%env(REDIS_URL)%'

    App\Command\LatestRatesCollectCommand:
        arguments:
            $symbols: '%env(csv:SYMBOLS)%'
            $redis: '@Predis\Client'

    App\Command\AvgRatesCollectCommand:
        arguments:
            $symbols: '%env(csv:SYMBOLS)%'
            $redis: '@Predis\Client'

    App\Controller\HomeController:
        arguments:
            $apiKey: '%env(API_KEY)%'
            $symbols: '%env(csv:SYMBOLS)%'

    App\Validator\Constraints\ValidPairValidator:
        arguments:
            $symbols: '%env(csv:SYMBOLS)%'
        tags:
            - { name: validator.constraint_validator }
