# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        storage_factory_id: session.storage.factory.native
        handler_id: null  # Use PHP's default session handler
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'  # Where sessions are stored

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
